export const appCards =  [
    {   
        src: require("../../images/myWorkPage/cardPics/app/blackRock.png").default, 
        alt: "BlackRock Tableau Dashboard Logo",
        title: "BlackRock Tableau Dashboard",
        desc: "In the summer of 2020, I interned with BlackRock where I got to work with a lot of data and represent it visually",
        href: "blackrock-tableau-dashboard", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/workout.png").default, 
        alt: "Workout Application Logo",
        title: "Workout Application",
        desc: "I worked with a team of 5 other students to work on a Workout app written in React Native",
        href: "workout-application", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/xv6.jpg").default, 
        alt: "Operating System Tinkering Logo",
        title: "Operating System Tinkering",
        desc: "I had the opporunity to dive into the workings of a basic OS by creating software applcations on one",
        href: "operating-system-tinkering", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/tiva.png").default, 
        alt: "TI Tiva Launchpad Games Logo",
        title: "TI Tiva Launchpad Games",
        desc: "I created 2 games written in C that ran on the Tiva Launchpad",
        href: "ti-tiva-launchpad-games", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/AI.png").default, 
        alt: "Artificial Intelligence Project Logo",
        title: "Artificial Intelligence Projects",
        desc: "During a summer class ( CS 540: Intro to AI ), I had the opportunity to work on a couple projects that put what was taught in class into practice",
        href: "artificial-intelligence-projects", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/bmi.png").default, 
        alt: "Introduction to Bioinformatics via Jupyter Notebooks Logo",
        title: "Introduction to Bioinformatics via Jupyter Notebooks",
        desc: "Through a class called BMI 576: Intro to Bioinformatics, I had the opporunity to apply technical skills onto a different field, Biology, to solve modern day problems.",
        href: "introduction-to-bioinformatics-via-jupyter-notebooks", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/eclipse.png").default,   
        alt: "Java Programs and Applications Logo",
        title: "Java Programs and Applications",
        desc: "Within 2 of my computer science classes, I was able to explore programming concepts with Java, including data structures, object oriented programming, and more",
        href: "java-programs-and-applications", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/551.png").default, 
        alt: "Blueooth Audio Receiver and Equalizer Logo",
        title: "Blueooth Audio Receiver and Equalizer",
        desc: "I alongside 3 other students designed a Blueooth audio receiver and equalizer that we wrote in Verilog, and synthezied and tested via emulation",
        href: "blueooth-audio-receiver-and-equalizer", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/552.png").default, 
        alt: "MIPS 16-bit 5-stage Pipelined Microprocessor Logo",
        title: "MIPS 16-bit 5-stage Pipelined Microprocessor",
        desc: "I and my partner in ECE 552: Intro to Computer Architecture, designed our very own MIPS 16-bit 5-stage pipelined microprocessor with forwarding enabled and cache in System Verilog",
        href: "mips-16-bit-5-stage-pipelined-microprocessor", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/app/cnn.png").default, 
        alt: "Convulutionary Neural Network Hardware Accelerator Logo",
        title: "Convulutionary Neural Network Hardware Accelerator",
        desc: "I worked within a team of 5 other students to build out a Convolutional Neural Network accelerator, designed to be able to do the required matrix math correctly with pretrained values. ",
        href: "convulutionary-neural-network-hardware-accelerator", 
    },

]