export const appCards =  [
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png'), 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },

]