export const videoCards =  [
    {   
        src: require("../../images/myWorkPage/cardPics/videos/loveonleash.png").default,
        alt: "Love on a Leash Logo",
        title: "Love on a Leash",
        desc: "As a volunteer opportunity, I created a video for Love on Leash, a nonprofit organization that provides therapy dogs for local organizations.",
        href: "love-on-a-leash", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/midlife.jpg").default,
        alt: "A Midlife Crisis But in College Logo",
        title: "A Midlife Crisis, But in College",
        desc: "This video was created for the Design Salon 2020, a competition hosted by the UW Libraries that asked participants to submit and share their digital works",
         href: "a-midlife-crisis-but-in-college", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/memepage.jpg").default,
        alt: "Videos For UW-Madison Memes For Milk Chugging Teens Logo",
        title: "Videos For UW-Madison Memes For Milk Chugging Teens",
        desc: "For three years within my college career, I helped run the UW-Madison Facebook meme page called UW-Madison Memes for Milk Chugging teens",
        href: "videos-for-uw-madison-memes-for-milk-chugging-teens", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/adclub.png").default,
        alt: "Advertisement Club Videos Logo",
        title: "Advertisement Club Videos",
        desc: "I created promo videos for local Madison, WI organizations and businesses such as Forward Madison FC, CAMPO, and Porter Coffee House",
        href: "advertisement-club-videos", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/blacksheep.jpg").default,
        alt: "Black Sheep Videos Logo",
        title: "Black Sheep Videos",
        desc: "I interned with the Black Sheep at UW-Madison throughout my second year (2018-2019) to create memes weekly relating to the university and recent events for their Instagram and Twitter accounts.",
        href: "black-sheep-videos", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/mealplan.jpg").default,
        alt: "Communication Arts 200 Video Logo",
        title: "Communication Arts 200 Video",
        desc: "Within CA 200: Introduction to Digital Communication, I made a video focusing on the required meal plan that new incoming UW student were required to participate in, and why I thought it was a bad idea",
         href: "communication-arts-200-video", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/videos/eddiemcdanger.jpg").default,
        alt: "Communication Arts 155 Video Logo",
        title: "Communication Arts 155 Video",
        desc: "Within CA 155: Introduction to Digital Media Production, I alongside another 2 students created a comical video that was a parody to survival shows that involved me, “Eddie McDanger” climbing up the iconic campus hill, Bascom Hill. ",
        href: "communication-arts-155-video", 
    },
]