export const videoCards =  [
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "SOMETHING Logo",
        title: "SOMETHING",
        desc: "SOMETHING",
        href: "/mywork/template", 
    },
]