export const websiteCards =  [
    {   
        src: require("../../images/myWorkPage/cardPics/website/mysite.png").default, 
        alt: "My Personal Website Logo",
        title: "My Personal Website",
        desc: "I designed and implemented my own personal website (this one!) using React and other web tools.",
        href: "personal-site", 
        use: "WebsiteTemplate", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/lacosechawebsite.png").default, 
        alt: "La Cosecha Tortilleria Logo",
        title: "La Cosecha Tortilleria Company Website",
        desc: "I designed and implemented a website for the La Cosecha Tortilleria Company, a tortilla business located in Madison, WI",
        href: "la-cosecha-tortilla", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/just.png").default, 
        alt: "JUST Logo",
        title: "Journal of Science and Technology (JUST)",
        desc: "I helped maintain the website used by JUST, a club at UW-Madison",
        href: "JUST", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/ncjs.png").default, 
        alt: "NCJS Logo",
        title: "National Collegiate Journal of Science (NCJS)",
        desc: "I designed and implemented a WordPress website for the National Collegiate Journal of Science",
        href: "NCJS", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/nm.jpg").default, 
        alt: "Risk Assessment and Aggregate Application",
        title: "Risk Assessment and Aggregate Application",
        desc: "Within my second summer with Northwestern Mutual, I and another intern created a prototype for a new way risk could be calculated and evaluated within the company.",
        href: "risk-assessment-and-aggregate-application", 
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/takeoff.png").default, 
        alt: "LiftOff Logo",
        title: "LiftOff",
        desc: "I, alongside 5 others, teamed up to create a web app called LiftOff, which was designed to streamline the onboarding experience for Northwestern Mutual interns.",
        href: "liftoff",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/codeForGood.jpeg").default, 
        alt: "Apprisen Logo",
        title: "Apprisen Website Redesign (JP Morgan Chase Hackathon)",
        desc: "I was in team within JP Morgan Chase's Code For Good Hackathon where we redesigned a website for a non-profit organization called Apprisen",
        href: "apprisen-website-redesign",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/nm2.jpg").default, 
        alt: "College Financial Literacy Web App Logo",
        title: "College Financial Literacy Web App",
        desc: "During my winter break of my freshman year, I and another intern worked on a prototype web app that would give high school and early college student much needed financial literacy tools.",
         href: "college-financial-literacy-web-app",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/longgame.png").default, 
        alt: "Logevity Game Logo",
        title: "The Longevity Game",
        desc: "Within Northwestern Mutual, I was a part of team that recreated an old Flash game called The Longevity Game with modern web tools.",
        href: "the-longevity-game",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/lis500.png").default,   
        alt: "Custom Implicit Bias Test Logo",
        title: "Custom Implicit Bias Test",
        desc: "My team and I created an online survey about implicit racial and gender biases. We built and tracked the survey and its results using HTML, CSS, and PHP.",
        href: "custom-implicit-bias-test",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/freesound.png").default,   
        alt: "Freesound Logo",
        title: "FreeSound Website Redesign",
        desc: "I created a mockup of a redesign of a website I frequented called FreeSound and created a prototype with React",
        href: "freesound-website-redesign",
    },
    {   
        src: require("../../images/myWorkPage/cardPics/website/arb.png").default, 
        alt: "University of Wisconsin-Arboretum Website Redesign",
        title: "University of Wisconsin-Arboretum Website Redesign",
        desc: "I was in team that redesigned the website used by the University of Wisconsin-Arboretum to be more useful to most users and to increase traffic and interactions",
        href: "university-of-wisconsin-arboretum-website-redesign",
    },
    
]