export const websiteCards =  [
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "My Personal Website Logo",
        title: "My Personal Website",
        desc: "I designed and implimented my own personal website (this one!) using React and other web tools.",
        href: "personal-site", 
        use: "WebsiteTemplate",
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "La Cosecha Tortilleria Logo",
        title: "La Cosecha Tortilleria Compnany Website",
        desc: "I designed and implimented a website for the La Cosecha Tortilleria Company, a tortilla business located in Madison, WI",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "JUST Logo",
        title: "Journal of Science and Technology (JUST)",
        desc: "I helped maintain the website used by JUST, a club at the UW-Madison campus",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "NCJS Logo",
        title: "National Collegiate Journal of Science (NCJS)",
        desc: "I designed and implimented a Wordpress website for the National Collegiate Journal of Science, an organization whose goal was to a home to academic research articles written by students across the country and facilitate conversations about STEM fields and advancements within them",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "LiftOff Logo",
        title: "LiftOff",
        desc: "I, alongside 5 others, teamed up to create a web app called Liftoff, designed to streamline the onboarding experience",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "Apprisen Logo",
        title: "Apprisen Website Redesign (JP Morgan Chase Hackathon)",
        desc: "I was in team within JP Morgan Chase's Code For Good Hackathon where we redesigned a website for a non-profit organzation called Aprisen",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "Logevity Game Logo",
        title: "The Longevity Game",
        desc: "Within Northwestern Mutual, I was a part of team that recreated an old Flash game called The Longevity Game with modern web tools.",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "Risk Assessment and Aggregate Application",
        title: "Risk Assessment and Aggregate Application",
        desc: "Within my second summer with Northwestern Mutual, I and another intern created a prototype for a new way risk could be calculated and evaluated within the company.",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "College Financial Literacy Web App Logo",
        title: "College Financial Literacy Web App",
        desc: "During my winter break within my freshman year, I and another intern worked on a prototype web app that would teach high school and early college student needed financial literacy tools.",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "Custom Implicit Bias TestLogo",
        title: "Custom Implicit Bias Test",
        desc: "I helped the team develop an online survey about implicit racial and gender biases. We built and tracked the survey using HTML, CSS, and PHP.",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "Freesound Logo",
        title: "Freesound Website Redesign",
        desc: "I created a mockup of a redesign of a website I frequented called FreeSound and created a prototype with React",
        href: "/mywork/template", 
    },
    {   
        src: require('../../images/placeholder.png').default, 
        alt: "University of Wisconsin-Arboretum Website Redesign",
        title: "University of Wisconsin-Arboretum Website Redesign",
        desc: "I was in team that redesigned the website used by the University of Wisconsin-Arboretum to be more useful to most users and to increase traffic and interations",
        href: "/mywork/template", 
    },
    
]